### ISSUE TITLE
Excelente trabajo!

### ISSUE THREAD

**Issue by crguezl** [ULL-MII-SYTWS-1920/p4-t2-networking-Omar97perez#2]
👍 @Omar97perez!

Te ha quedado excelente. ¡Muy bien las pruebas y la CI en Travis!

Incidencias (puedo estar equivocado, ya me dices). Corrige lo que puedas:

* En el README.md de la entrega el enlace 

```
[Clickar para ver mejor la explicación](https://ull-mii-sytws-1920.github.io/p3-t1-c3-http-p2-t1-c3-filesystem-omarperezznakar/)
```
apunta a la de http no a esta. Debería ser: https://ull-mii-sytws-1920.github.io/p4-t2-networking-Omar97perez/. Pon el enlace también en la descripción (arriba)

* Es un requisito que añadí tarde pero si lo haces mejor. En la 
[práctica p4-t2-networking](https://ull-mii-sytws-1920.github.io/tema2-async/practicas/p4-t2-networking/) les pido que experimenten con *GitHub Actions* para el CI

> Utilice GitHub Actions para añadir Integración Continua y realizar sus pruebas en GitHub

¿Puedes intentarlo? Si no, lo dejas para otra práctica

* La documentación generada debería estar publicada en el repo

* En el tutorial dice:

>... se ha creado un script en el apartado “scripts” dentro del package.json para un funcionamiento mucho más sencillo

No lo encuentro en el `package.json` del repo

* Cuando ejecuto el chat server del reto no me funciona correctamente:

![Captura de pantalla 2019-11-12 a las 9 02 24](https://user-images.githubusercontent.com/1142554/68657234-39392380-052b-11ea-9fe4-f82845b5400d.png)

**Comment by Omar97perez** [comment]
Buenos días profesor, acabo de revisar lo siguientes fallos:
- **En el README.md de la entrega el enlace:** esta solucionado y le puse el enlace en la parte superior.
- **Experimentación con GitHub Actions para el CI**: desde que tenga un momento lo realizo y si le parece bien se lo entrego junto con la práctica 5.
- **La documentación generada debería estar publicada en el repo:** si se refiere a la página web de jekyll está dentro de la carpeta "docs" para poder desplegar la github pages. 
- **Script Json.packege.json** me refería a la parte resaltada en azul (perdón si me expliqué mal)
![image](https://user-images.githubusercontent.com/36955113/68664292-077a8980-0538-11ea-893c-1b697c0f6575.png)
- **Chat** lo realize usando telnet (debido a que desde windows no pude descargar nc), con telnet funciona correctamente le paso una captura hecha ahora mismo:
![image](https://user-images.githubusercontent.com/36955113/68665016-37765c80-0539-11ea-9e75-587d0e1de698.png)

Muchas gracias por la atención, un saludo,
Omar.

**Comment by crguezl** [comment]
Hola Omar,

> - **En el README.md de la entrega el enlace:** esta solucionado y le puse el enlace en la parte superior.

¡Perfecto!

>- **Experimentación con GitHub Actions para el CI**: desde que tenga un momento lo realizo y si le parece bien se lo entrego junto con la práctica 5.

¡Claro! ¡Gracias!

> - **La documentación generada debería estar publicada en el repo:** si se refiere a la página web de jekyll está dentro de la carpeta "docs" para poder desplegar la github pages. 

No, me refería a la generada. Pero no tiene importancia. Déjalo como está

> - **Script Json.packege.json** me refería a la parte resaltada en azul (perdón si me expliqué mal)
![image](https://user-images.githubusercontent.com/36955113/68664292-077a8980-0538-11ea-893c-1b697c0f6575.png)

Ah, OK

> - **Chat** lo realize usando telnet (debido a que desde windows no pude descargar nc), con telnet funciona correctamente le paso una captura hecha ahora mismo:
![image](https://user-images.githubusercontent.com/36955113/68665016-37765c80-0539-11ea-9e75-587d0e1de698.png)

Estupendo.

Gracias Omar
